### ISSUE TITLE
champ "liste destinataires" et désactivation plugin

### ISSUE THREAD

**Issue by nanart59** [franck-paul/contactMe#1]
Bonjour,
le champ "liste des destinataires" semble **obligatoire** alors que le label indique: _Videz la liste des destinataires pour désactiver la page de contact.
En conséquence, si on vide la liste des destinataires, on ne peut enregistrer la configuration.
message: "Veuillez compléter ce champ"

**Comment by franck-paul** [comment]
Ah oui tu as raison, je vais revoir ça
