### ISSUE TITLE
Oubli dans les default template

### ISSUE THREAD

**Issue by pichel26** [franck-paul/contactMe#4]
Bonjour, 
les templates de contact fournis n'ont pas le hook qui permet aux autres plugins de rajouter leurs propres options, comme par exemple le captcha.
Il faudrait rajouter en bas du formulaire le hook (nous avons recopié celui qui était présent dans les précédentes versions) : 
<p class="field">{{tpl:SysBehavior behavior="publicCommentFormAfterContent"}}</p>

Et ainsi notre dispositif antispam est de nouveau apparu en dessous du formulaire.

Merci pour le boulot en tout cas

Michel
SARL Vertacoo

**Comment by franck-paul** [comment]
En fait ça n'est pas un oubli, un formulaire de contact (via mail) n'est pas un formulaire de dépôt d'un commentaire.

Par contre je peux tout à fait ajouter quelques behaviors, libre aux plugins de les gérer aussi.

**Comment by pichel26** [comment]
Bonjour, 
tout à fait d'accord, ça fait un peu étrange que le behavior soit un behavior de commentaire, cependant ça permet de rajouter une vérification antispam et même un captcha si on veut, ce qui est très intéressant pour le fonctionnement du formulaire.
Alors le behavior de commentaire n'est peut-être pas idéal, mais je vis bien avec :-)
Donc ça vaudrait en effet le coup de rajouter un behavior qui permette de rajouter des champs depuis d'autres plugins.

merci
